# Install script for directory: G:/gitRepositories/libigl_CGAL_openGL

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/libigl")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/Debug/igl.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/Release/igl.lib")
  elseif(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE STATIC_LIBRARY FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/RelWithDebInfo/igl.lib")
  endif()
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/igl" TYPE FILE FILES
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/AABB.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ARAPEnergyType.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/AtA_cached.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/C_STR.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Camera.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/EPS.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/FastWindingNumberForSoups.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/FileEncoding.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/HalfEdgeIterator.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Hit.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/IndexComparison.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/LinSpaced.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/MappingEnergyType.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/MeshBooleanType.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/MshLoader.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/MshSaver.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/NormalType.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ONE.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/PI.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/REDRUM.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/STR.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Singular_Value_Decomposition_Givens_QR_Factorization_Kernel.hpp"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Singular_Value_Decomposition_Jacobi_Conjugation_Kernel.hpp"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Singular_Value_Decomposition_Kernel_Declarations.hpp"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Singular_Value_Decomposition_Main_Kernel_Body.hpp"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Singular_Value_Decomposition_Preamble.hpp"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/SolverStatus.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/SortableRow.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Timer.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/Viewport.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/WindingNumberAABB.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/WindingNumberMethod.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/WindingNumberTree.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ZERO.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/accumarray.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/active_set.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/adjacency_list.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/adjacency_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/all.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/all_pairs_distances.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ambient_occlusion.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/angular_distance.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/any.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/any_of.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/arap.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/arap_dof.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/arap_linear_block.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/arap_rhs.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/average_from_edges_onto_vertices.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/average_onto_faces.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/average_onto_vertices.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/avg_edge_length.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/axis_angle_to_quat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/barycenter.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/barycentric_coordinates.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/barycentric_interpolation.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/basename.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bbw.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bezier.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bfs.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bfs_orient.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/biharmonic_coordinates.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bijective_composite_harmonic_mapping.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/blkdiag.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/blue_noise.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bone_parents.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/boundary_conditions.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/boundary_facets.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/boundary_loop.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bounding_box.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/bounding_box_diagonal.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/canonical_quaternions.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ceil.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/centroid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/circulation.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/circumradius.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/collapse_edge.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/collapse_small_triangles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/colon.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/colormap.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/column_to_quats.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/columnize.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/comb_cross_field.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/comb_frame_field.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/comb_line_field.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/combine.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/compute_frame_field_bisectors.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/connect_boundary_to_infinity.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/connected_components.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cotmatrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cotmatrix_entries.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cotmatrix_intrinsic.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/count.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/covariance_scatter_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cr_vector_curvature_correction.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cr_vector_laplacian.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cr_vector_mass.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cross.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cross_field_mismatch.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/crouzeix_raviart_cotmatrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/crouzeix_raviart_massmatrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cumprod.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cumsum.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/curved_hessian_energy.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cut_mesh.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cut_mesh_from_singularities.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cut_to_disk.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/cylinder.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dated_copy.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/decimate.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/decimate_callback_types.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/decimate_trivial_callbacks.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/default_num_threads.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/deform_skeleton.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/delaunay_triangulation.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/deprecated.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dfs.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/diag.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dihedral_angles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dijkstra.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/direct_delta_mush.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/directed_edge_orientations.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/directed_edge_parents.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dirname.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dot.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dot_row.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/doublearea.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dqs.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/dual_contouring.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ears.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_collapse_is_valid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_exists_near.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_flaps.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_lengths.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_midpoints.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_topology.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edge_vectors.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/edges_to_path.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/eigs.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/euler_characteristic.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/exact_geodesic.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/example_fun.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/exploded_view.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/extension.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/exterior_edges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/extract_manifold_patches.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/extract_non_manifold_edge_curves.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/face_areas.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/face_occurrences.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/faces_first.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/facet_adjacency_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/facet_components.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/false_barycentric_subdivision.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/fast_winding_number.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/file_contents_as_string.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/file_dialog_open.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/file_dialog_save.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/file_exists.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/file_utils.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/find.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/find_cross_field_singularities.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/find_zero.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/fit_cubic_bezier.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/fit_plane.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/fit_rotations.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/flip_avoiding_line_search.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/flip_edge.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/flipped_triangles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/flood_fill.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/floor.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/for_each.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/forward_kinematics.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/frame_field_deformer.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/frame_to_cross_field.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/frustum.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/gaussian_curvature.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/get_seconds.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/get_seconds_hires.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/grad.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/grad_intrinsic.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/grid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/grid_search.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/group_sum_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/guess_extension.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/harmonic.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/harwell_boeing.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/hausdorff.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/heat_geodesics.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/hessian.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/hessian_energy.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/histc.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/hsv_to_rgb.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/igl_inline.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/in_element.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/infinite_cost_stopping_condition.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/inradius.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/internal_angles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/intersect.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/intrinsic_delaunay_cotmatrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/intrinsic_delaunay_triangulation.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/invert_diag.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_border_vertex.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_boundary_edge.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_delaunay.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_dir.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_edge_manifold.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_file.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_intrinsic_delaunay.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_irregular_vertex.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_planar.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_readable.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_sparse.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_stl.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_symmetric.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_vertex_manifold.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/is_writable.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/isdiag.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ismember.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/isolines.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/isolines_map.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/iterative_closest_point.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/jet.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/kelvinlets.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/kkt_inverse.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/knn.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/launch_medit.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/lbs_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/lexicographic_triangulation.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/limit_faces.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/line_field_mismatch.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/line_search.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/line_segment_in_rectangle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/linprog.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/list_to_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/local_basis.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/look_at.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/loop.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/lscm.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/map_vertices_to_circle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mapping_energy_with_jacobians.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/march_cube.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/marching_cubes.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/marching_cubes_tables.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/marching_tets.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/massmatrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/massmatrix_intrinsic.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mat_max.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mat_min.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mat_to_quat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/material_colors.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/matlab_format.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/matrix_to_list.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/max.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/max_faces_stopping_condition.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/max_size.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/median.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/min.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/min_heap.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/min_quad_with_fixed.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/min_quad_with_fixed.impl.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/min_size.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mod.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mode.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/mvc.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/nchoosek.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/next_filename.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/normal_derivative.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/normalize_quat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/normalize_row_lengths.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/normalize_row_sums.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/null.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/octree.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/offset_surface.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/on_boundary.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/orient_halfedges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/orient_outward.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/orientable_patches.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/oriented_facets.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/orth.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ortho.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/outer_element.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/parallel_for.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/parallel_transport_angles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/partition.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/parula.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/path_to_edges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/path_to_executable.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/pathinfo.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/per_corner_normals.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/per_edge_normals.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/per_face_normals.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/per_vertex_attribute_smoothing.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/per_vertex_normals.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/per_vertex_point_to_plane_quadrics.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/piecewise_constant_winding_number.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/pinv.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/planarize_quad_mesh.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/point_in_circle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/point_mesh_squared_distance.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/point_simplex_squared_distance.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/polar_dec.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/polar_svd.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/polar_svd3x3.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/polygon_corners.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/polygons_to_triangles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/principal_curvature.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/print_ijv.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/print_vector.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/procrustes.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/project.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/project_isometrically_to_plane.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/project_to_line.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/project_to_line_segment.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/projection_constraint.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/pseudonormal_test.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/pso.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/qslim.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/qslim_optimal_collapse_edge_callbacks.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quad_grid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quad_planarity.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quadprog.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quadric_binary_plus_operator.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quat_conjugate.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quat_mult.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quat_to_axis_angle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quat_to_mat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/quats_to_column.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ramer_douglas_peucker.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/random_dir.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/random_points_on_mesh.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/random_quaternion.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/random_search.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/randperm.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ray_box_intersect.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ray_mesh_intersect.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/ray_sphere_intersect.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readBF.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readCSV.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readDMAT.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readMESH.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readMSH.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readNODE.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readOBJ.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readOFF.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readPLY.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readSTL.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readTGF.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/readWRL.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/read_triangle_mesh.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/redux.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/remesh_along_isoline.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/remove_duplicate_vertices.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/remove_unreferenced.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/reorder.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/repdiag.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/repmat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/resolve_duplicated_faces.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/rgb_to_hsv.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/rigid_alignment.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/rotate_by_quat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/rotate_vectors.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/rotation_matrix_from_directions.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/round.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/rows_to_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sample_edges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/scalar_to_cr_vector_gradient.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/screen_space_selection.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/seam_edges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/segment_segment_intersect.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/serialize.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/setdiff.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/setunion.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/setxor.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/shape_diameter_function.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/shapeup.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sharp_edges.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/shortest_edge_and_midpoint.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/signed_angle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/signed_distance.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/simplify_polyhedron.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/slice.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/slice_cached.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/slice_into.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/slice_mask.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/slice_sorted.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/slim.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/smooth_corner_adjacency.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/snap_points.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/snap_to_canonical_view_quat.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/snap_to_fixed_up.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/solid_angle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sort.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sort_angles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sort_triangles.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sort_vectors_ccw.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sortrows.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sparse.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sparse_cached.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sparse_voxel_grid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/speye.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/squared_edge_lengths.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/stdin_to_temp.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/straighten_seams.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/string_utils.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/sum.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/svd3x3.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/svd3x3_avx.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/svd3x3_sse.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/swept_volume.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/swept_volume_bounding_box.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/swept_volume_signed_distance.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/tan_half_angle.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/tet_tet_adjacency.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/tetrahedralized_grid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/tinyply.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/topological_hole_fill.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/trackball.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/transpose_blocks.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/triangle_fan.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/triangle_triangle_adjacency.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/triangles_from_strip.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/triangulated_grid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/two_axis_valuator_fixed_up.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/uniformly_sample_two_manifold.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unique.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unique_edge_map.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unique_rows.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unique_simplices.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unproject.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unproject_in_mesh.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unproject_on_line.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unproject_on_plane.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unproject_onto_mesh.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unproject_ray.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/unzip_corners.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/upsample.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/vector_area_matrix.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/verbose.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/vertex_components.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/vertex_triangle_adjacency.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/volume.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/voxel_grid.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/winding_number.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeBF.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeDMAT.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeMESH.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeMSH.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeOBJ.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeOFF.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writePLY.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeSTL.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeTGF.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/writeWRL.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/write_triangle_mesh.h"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/igl/copyleft" TYPE FILE FILES
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/copyleft/marching_cubes.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/copyleft/marching_cubes_tables.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/copyleft/progressive_hulls.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/copyleft/progressive_hulls_cost_and_placement.h"
    "G:/gitRepositories/libigl_CGAL_openGL/include/igl/copyleft/quadprog.h"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/libigl/cmake" TYPE FILE FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/libigl-config.cmake")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/share/libigl/cmake/libigl-export.cmake")
    file(DIFFERENT _cmake_export_file_changed FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/share/libigl/cmake/libigl-export.cmake"
         "G:/gitRepositories/libigl_CGAL_openGL/build32/CMakeFiles/Export/b00fa334c3cab0b257cdaf2865e998b7/libigl-export.cmake")
    if(_cmake_export_file_changed)
      file(GLOB _cmake_old_config_files "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/share/libigl/cmake/libigl-export-*.cmake")
      if(_cmake_old_config_files)
        string(REPLACE ";" ", " _cmake_old_config_files_text "${_cmake_old_config_files}")
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/share/libigl/cmake/libigl-export.cmake\" will be replaced.  Removing files [${_cmake_old_config_files_text}].")
        unset(_cmake_old_config_files_text)
        file(REMOVE ${_cmake_old_config_files})
      endif()
      unset(_cmake_old_config_files)
    endif()
    unset(_cmake_export_file_changed)
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/libigl/cmake" TYPE FILE FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/CMakeFiles/Export/b00fa334c3cab0b257cdaf2865e998b7/libigl-export.cmake")
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/libigl/cmake" TYPE FILE FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/CMakeFiles/Export/b00fa334c3cab0b257cdaf2865e998b7/libigl-export-debug.cmake")
  endif()
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/libigl/cmake" TYPE FILE FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/CMakeFiles/Export/b00fa334c3cab0b257cdaf2865e998b7/libigl-export-relwithdebinfo.cmake")
  endif()
  if(CMAKE_INSTALL_CONFIG_NAME MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/libigl/cmake" TYPE FILE FILES "G:/gitRepositories/libigl_CGAL_openGL/build32/CMakeFiles/Export/b00fa334c3cab0b257cdaf2865e998b7/libigl-export-release.cmake")
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/CoMISo/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/glad/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/glfw/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/imgui/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/stb_image/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/tetgen/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/triangle/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/predicates/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/tutorial/cmake_install.cmake")
  include("G:/gitRepositories/libigl_CGAL_openGL/build32/tests/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "G:/gitRepositories/libigl_CGAL_openGL/build32/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
